import type { RussianPlacementMetaQuestion, RussianPlacementQuestion } from '@/lib/russianPlacementTypes';

export const RUSSIAN_PLACEMENT_META_QUESTIONS: RussianPlacementMetaQuestion[] = [
  {
    id: 'goal',
    promptKey: 'languages.placementV2.meta.goal.prompt',
    options: [
      { id: 'prep_exam', labelKey: 'languages.placementV2.meta.goal.options.prep_exam' },
      { id: 'university_study', labelKey: 'languages.placementV2.meta.goal.options.university_study' },
      { id: 'daily_life', labelKey: 'languages.placementV2.meta.goal.options.daily_life' },
    ],
  },
  {
    id: 'urgency',
    promptKey: 'languages.placementV2.meta.urgency.prompt',
    options: [
      { id: '1_month', labelKey: 'languages.placementV2.meta.urgency.options.1_month' },
      { id: '3_months', labelKey: 'languages.placementV2.meta.urgency.options.3_months' },
      { id: 'no_deadline', labelKey: 'languages.placementV2.meta.urgency.options.no_deadline' },
    ],
  },
  {
    id: 'intendedTrack',
    promptKey: 'languages.placementV2.meta.intendedTrack.prompt',
    options: [
      { id: 'medicine', labelKey: 'languages.placementV2.meta.intendedTrack.options.medicine' },
      { id: 'engineering', labelKey: 'languages.placementV2.meta.intendedTrack.options.engineering' },
      { id: 'humanities_social', labelKey: 'languages.placementV2.meta.intendedTrack.options.humanities_social' },
    ],
  },
  {
    id: 'priorStudy',
    promptKey: 'languages.placementV2.meta.priorStudy.prompt',
    options: [
      { id: 'none', labelKey: 'languages.placementV2.meta.priorStudy.options.none' },
      { id: 'some_basics', labelKey: 'languages.placementV2.meta.priorStudy.options.some_basics' },
      { id: 'classroom_experience', labelKey: 'languages.placementV2.meta.priorStudy.options.classroom_experience' },
    ],
  },
];

export const RUSSIAN_PLACEMENT_QUESTION_BANK: RussianPlacementQuestion[] = [
  {
    id: 'a_01',
    block_code: 'A_SCRIPT',
    subskill: 'letter_recognition',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_01.prompt',
    instructionKey: 'languages.placementV2.bank.a_01.instruction',
    contentKey: 'languages.placementV2.bank.a_01.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_01.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_01.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_01.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_01.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'a_02',
    block_code: 'A_SCRIPT',
    subskill: 'sound_mapping',
    difficulty: 1 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.a_02.prompt',
    instructionKey: 'languages.placementV2.bank.a_02.instruction',
    contentKey: 'languages.placementV2.bank.a_02.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_02.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_02.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_02.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_02.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'a_03',
    block_code: 'A_SCRIPT',
    subskill: 'visual_distinction',
    difficulty: 1 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.a_03.prompt',
    instructionKey: 'languages.placementV2.bank.a_03.instruction',
    contentKey: 'languages.placementV2.bank.a_03.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_03.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_03.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_03.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_03.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'a_04',
    block_code: 'A_SCRIPT',
    subskill: 'simple_decoding',
    difficulty: 2 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_04.prompt',
    instructionKey: 'languages.placementV2.bank.a_04.instruction',
    contentKey: 'languages.placementV2.bank.a_04.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_04.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_04.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_04.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_04.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'a_05',
    block_code: 'A_SCRIPT',
    subskill: 'letter_recognition',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.a_05.prompt',
    instructionKey: 'languages.placementV2.bank.a_05.instruction',
    contentKey: 'languages.placementV2.bank.a_05.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_05.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_05.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_05.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_05.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'a_06',
    block_code: 'A_SCRIPT',
    subskill: 'sound_mapping',
    difficulty: 2 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.a_06.prompt',
    instructionKey: 'languages.placementV2.bank.a_06.instruction',
    contentKey: 'languages.placementV2.bank.a_06.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_06.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_06.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_06.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_06.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'a_07',
    block_code: 'A_SCRIPT',
    subskill: 'visual_distinction',
    difficulty: 3 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_07.prompt',
    instructionKey: 'languages.placementV2.bank.a_07.instruction',
    contentKey: 'languages.placementV2.bank.a_07.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_07.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_07.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_07.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_07.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'a_08',
    block_code: 'A_SCRIPT',
    subskill: 'simple_decoding',
    difficulty: 3 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.a_08.prompt',
    instructionKey: 'languages.placementV2.bank.a_08.instruction',
    contentKey: 'languages.placementV2.bank.a_08.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_08.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_08.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_08.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_08.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'a_09',
    block_code: 'A_SCRIPT',
    subskill: 'letter_recognition',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.a_09.prompt',
    instructionKey: 'languages.placementV2.bank.a_09.instruction',
    contentKey: 'languages.placementV2.bank.a_09.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_09.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_09.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_09.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_09.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'a_10',
    block_code: 'A_SCRIPT',
    subskill: 'sound_mapping',
    difficulty: 4 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_10.prompt',
    instructionKey: 'languages.placementV2.bank.a_10.instruction',
    contentKey: 'languages.placementV2.bank.a_10.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_10.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_10.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_10.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_10.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'a_11',
    block_code: 'A_SCRIPT',
    subskill: 'visual_distinction',
    difficulty: 4 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.a_11.prompt',
    instructionKey: 'languages.placementV2.bank.a_11.instruction',
    contentKey: 'languages.placementV2.bank.a_11.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_11.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_11.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_11.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_11.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'a_12',
    block_code: 'A_SCRIPT',
    subskill: 'simple_decoding',
    difficulty: 4 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.a_12.prompt',
    instructionKey: 'languages.placementV2.bank.a_12.instruction',
    contentKey: 'languages.placementV2.bank.a_12.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_12.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_12.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_12.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_12.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'a_13',
    block_code: 'A_SCRIPT',
    subskill: 'letter_recognition',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_13.prompt',
    instructionKey: 'languages.placementV2.bank.a_13.instruction',
    contentKey: 'languages.placementV2.bank.a_13.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_13.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_13.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_13.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_13.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'a_14',
    block_code: 'A_SCRIPT',
    subskill: 'sound_mapping',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.a_14.prompt',
    instructionKey: 'languages.placementV2.bank.a_14.instruction',
    contentKey: 'languages.placementV2.bank.a_14.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_14.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_14.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_14.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_14.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'a_15',
    block_code: 'A_SCRIPT',
    subskill: 'visual_distinction',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_recognition',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.a_15.prompt',
    instructionKey: 'languages.placementV2.bank.a_15.instruction',
    contentKey: 'languages.placementV2.bank.a_15.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_15.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_15.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_15.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_15.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'a_16',
    block_code: 'A_SCRIPT',
    subskill: 'simple_decoding',
    difficulty: 5 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'script_decoding',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.a_16.prompt',
    instructionKey: 'languages.placementV2.bank.a_16.instruction',
    contentKey: 'languages.placementV2.bank.a_16.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.a_16.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.a_16.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.a_16.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.a_16.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_01',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_01.prompt',
    instructionKey: 'languages.placementV2.bank.b_01.instruction',
    contentKey: 'languages.placementV2.bank.b_01.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_01.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_01.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_01.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_01.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_02',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 1 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_02.prompt',
    instructionKey: 'languages.placementV2.bank.b_02.instruction',
    contentKey: 'languages.placementV2.bank.b_02.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_02.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_02.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_02.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_02.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_03',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 1 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_03.prompt',
    instructionKey: 'languages.placementV2.bank.b_03.instruction',
    contentKey: 'languages.placementV2.bank.b_03.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_03.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_03.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_03.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_03.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_04',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_04.prompt',
    instructionKey: 'languages.placementV2.bank.b_04.instruction',
    contentKey: 'languages.placementV2.bank.b_04.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_04.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_04.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_04.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_04.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_05',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_05.prompt',
    instructionKey: 'languages.placementV2.bank.b_05.instruction',
    contentKey: 'languages.placementV2.bank.b_05.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_05.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_05.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_05.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_05.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_06',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 2 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_06.prompt',
    instructionKey: 'languages.placementV2.bank.b_06.instruction',
    contentKey: 'languages.placementV2.bank.b_06.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_06.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_06.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_06.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_06.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_07',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 2 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_07.prompt',
    instructionKey: 'languages.placementV2.bank.b_07.instruction',
    contentKey: 'languages.placementV2.bank.b_07.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_07.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_07.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_07.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_07.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_08',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_08.prompt',
    instructionKey: 'languages.placementV2.bank.b_08.instruction',
    contentKey: 'languages.placementV2.bank.b_08.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_08.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_08.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_08.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_08.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_09',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_09.prompt',
    instructionKey: 'languages.placementV2.bank.b_09.instruction',
    contentKey: 'languages.placementV2.bank.b_09.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_09.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_09.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_09.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_09.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_10',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 2 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_10.prompt',
    instructionKey: 'languages.placementV2.bank.b_10.instruction',
    contentKey: 'languages.placementV2.bank.b_10.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_10.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_10.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_10.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_10.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_11',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 3 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_11.prompt',
    instructionKey: 'languages.placementV2.bank.b_11.instruction',
    contentKey: 'languages.placementV2.bank.b_11.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_11.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_11.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_11.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_11.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_12',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_12.prompt',
    instructionKey: 'languages.placementV2.bank.b_12.instruction',
    contentKey: 'languages.placementV2.bank.b_12.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_12.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_12.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_12.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_12.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_13',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_13.prompt',
    instructionKey: 'languages.placementV2.bank.b_13.instruction',
    contentKey: 'languages.placementV2.bank.b_13.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_13.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_13.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_13.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_13.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_14',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 3 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_14.prompt',
    instructionKey: 'languages.placementV2.bank.b_14.instruction',
    contentKey: 'languages.placementV2.bank.b_14.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_14.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_14.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_14.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_14.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_15',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 3 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_15.prompt',
    instructionKey: 'languages.placementV2.bank.b_15.instruction',
    contentKey: 'languages.placementV2.bank.b_15.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_15.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_15.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_15.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_15.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_16',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_16.prompt',
    instructionKey: 'languages.placementV2.bank.b_16.instruction',
    contentKey: 'languages.placementV2.bank.b_16.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_16.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_16.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_16.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_16.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_17',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_17.prompt',
    instructionKey: 'languages.placementV2.bank.b_17.instruction',
    contentKey: 'languages.placementV2.bank.b_17.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_17.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_17.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_17.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_17.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_18',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 4 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_18.prompt',
    instructionKey: 'languages.placementV2.bank.b_18.instruction',
    contentKey: 'languages.placementV2.bank.b_18.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_18.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_18.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_18.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_18.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_19',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 4 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_19.prompt',
    instructionKey: 'languages.placementV2.bank.b_19.instruction',
    contentKey: 'languages.placementV2.bank.b_19.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_19.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_19.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_19.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_19.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_20',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_20.prompt',
    instructionKey: 'languages.placementV2.bank.b_20.instruction',
    contentKey: 'languages.placementV2.bank.b_20.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_20.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_20.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_20.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_20.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_21',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_21.prompt',
    instructionKey: 'languages.placementV2.bank.b_21.instruction',
    contentKey: 'languages.placementV2.bank.b_21.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_21.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_21.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_21.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_21.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_22',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_22.prompt',
    instructionKey: 'languages.placementV2.bank.b_22.instruction',
    contentKey: 'languages.placementV2.bank.b_22.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_22.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_22.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_22.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_22.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_23',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_23.prompt',
    instructionKey: 'languages.placementV2.bank.b_23.instruction',
    contentKey: 'languages.placementV2.bank.b_23.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_23.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_23.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_23.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_23.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_24',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_24.prompt',
    instructionKey: 'languages.placementV2.bank.b_24.instruction',
    contentKey: 'languages.placementV2.bank.b_24.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_24.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_24.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_24.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_24.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'b_25',
    block_code: 'B_GENERAL',
    subskill: 'high_frequency_vocabulary',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_25.prompt',
    instructionKey: 'languages.placementV2.bank.b_25.instruction',
    contentKey: 'languages.placementV2.bank.b_25.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_25.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_25.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_25.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_25.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'b_26',
    block_code: 'B_GENERAL',
    subskill: 'sentence_meaning',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.b_26.prompt',
    instructionKey: 'languages.placementV2.bank.b_26.instruction',
    contentKey: 'languages.placementV2.bank.b_26.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_26.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_26.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_26.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_26.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'b_27',
    block_code: 'B_GENERAL',
    subskill: 'phrase_comprehension',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_vocabulary',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.b_27.prompt',
    instructionKey: 'languages.placementV2.bank.b_27.instruction',
    contentKey: 'languages.placementV2.bank.b_27.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_27.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_27.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_27.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_27.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'b_28',
    block_code: 'B_GENERAL',
    subskill: 'grammar_context',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.b_28.prompt',
    instructionKey: 'languages.placementV2.bank.b_28.instruction',
    contentKey: 'languages.placementV2.bank.b_28.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.b_28.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.b_28.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.b_28.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.b_28.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'c_01',
    block_code: 'C_COMPREHENSION',
    subskill: 'grammar_in_context',
    difficulty: 1 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_01.prompt',
    instructionKey: 'languages.placementV2.bank.c_01.instruction',
    contentKey: 'languages.placementV2.bank.c_01.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_01.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_01.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_01.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_01.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'c_02',
    block_code: 'C_COMPREHENSION',
    subskill: 'short_reading',
    difficulty: 1 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_02.prompt',
    instructionKey: 'languages.placementV2.bank.c_02.instruction',
    contentKey: 'languages.placementV2.bank.c_02.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_02.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_02.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_02.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_02.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'c_03',
    block_code: 'C_COMPREHENSION',
    subskill: 'ordering_structure',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_03.prompt',
    instructionKey: 'languages.placementV2.bank.c_03.instruction',
    contentKey: 'languages.placementV2.bank.c_03.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_03.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_03.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_03.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_03.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'c_04',
    block_code: 'C_COMPREHENSION',
    subskill: 'fill_context',
    difficulty: 1 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_04.prompt',
    instructionKey: 'languages.placementV2.bank.c_04.instruction',
    contentKey: 'languages.placementV2.bank.c_04.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_04.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_04.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_04.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_04.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'c_05',
    block_code: 'C_COMPREHENSION',
    subskill: 'grammar_in_context',
    difficulty: 2 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_05.prompt',
    instructionKey: 'languages.placementV2.bank.c_05.instruction',
    contentKey: 'languages.placementV2.bank.c_05.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_05.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_05.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_05.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_05.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'c_06',
    block_code: 'C_COMPREHENSION',
    subskill: 'short_reading',
    difficulty: 2 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_06.prompt',
    instructionKey: 'languages.placementV2.bank.c_06.instruction',
    contentKey: 'languages.placementV2.bank.c_06.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_06.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_06.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_06.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_06.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'c_07',
    block_code: 'C_COMPREHENSION',
    subskill: 'ordering_structure',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_07.prompt',
    instructionKey: 'languages.placementV2.bank.c_07.instruction',
    contentKey: 'languages.placementV2.bank.c_07.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_07.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_07.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_07.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_07.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'c_08',
    block_code: 'C_COMPREHENSION',
    subskill: 'fill_context',
    difficulty: 2 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_08.prompt',
    instructionKey: 'languages.placementV2.bank.c_08.instruction',
    contentKey: 'languages.placementV2.bank.c_08.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_08.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_08.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_08.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_08.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'c_09',
    block_code: 'C_COMPREHENSION',
    subskill: 'grammar_in_context',
    difficulty: 3 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_09.prompt',
    instructionKey: 'languages.placementV2.bank.c_09.instruction',
    contentKey: 'languages.placementV2.bank.c_09.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_09.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_09.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_09.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_09.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'c_10',
    block_code: 'C_COMPREHENSION',
    subskill: 'short_reading',
    difficulty: 3 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_10.prompt',
    instructionKey: 'languages.placementV2.bank.c_10.instruction',
    contentKey: 'languages.placementV2.bank.c_10.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_10.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_10.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_10.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_10.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'c_11',
    block_code: 'C_COMPREHENSION',
    subskill: 'ordering_structure',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_11.prompt',
    instructionKey: 'languages.placementV2.bank.c_11.instruction',
    contentKey: 'languages.placementV2.bank.c_11.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_11.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_11.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_11.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_11.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'c_12',
    block_code: 'C_COMPREHENSION',
    subskill: 'fill_context',
    difficulty: 3 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_12.prompt',
    instructionKey: 'languages.placementV2.bank.c_12.instruction',
    contentKey: 'languages.placementV2.bank.c_12.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_12.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_12.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_12.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_12.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'c_13',
    block_code: 'C_COMPREHENSION',
    subskill: 'grammar_in_context',
    difficulty: 4 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_13.prompt',
    instructionKey: 'languages.placementV2.bank.c_13.instruction',
    contentKey: 'languages.placementV2.bank.c_13.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_13.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_13.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_13.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_13.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'c_14',
    block_code: 'C_COMPREHENSION',
    subskill: 'short_reading',
    difficulty: 4 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_14.prompt',
    instructionKey: 'languages.placementV2.bank.c_14.instruction',
    contentKey: 'languages.placementV2.bank.c_14.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_14.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_14.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_14.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_14.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'c_15',
    block_code: 'C_COMPREHENSION',
    subskill: 'ordering_structure',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_15.prompt',
    instructionKey: 'languages.placementV2.bank.c_15.instruction',
    contentKey: 'languages.placementV2.bank.c_15.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_15.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_15.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_15.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_15.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'c_16',
    block_code: 'C_COMPREHENSION',
    subskill: 'fill_context',
    difficulty: 4 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_16.prompt',
    instructionKey: 'languages.placementV2.bank.c_16.instruction',
    contentKey: 'languages.placementV2.bank.c_16.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_16.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_16.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_16.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_16.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'c_17',
    block_code: 'C_COMPREHENSION',
    subskill: 'grammar_in_context',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_17.prompt',
    instructionKey: 'languages.placementV2.bank.c_17.instruction',
    contentKey: 'languages.placementV2.bank.c_17.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_17.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_17.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_17.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_17.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'c_18',
    block_code: 'C_COMPREHENSION',
    subskill: 'short_reading',
    difficulty: 5 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.c_18.prompt',
    instructionKey: 'languages.placementV2.bank.c_18.instruction',
    contentKey: 'languages.placementV2.bank.c_18.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_18.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_18.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_18.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_18.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'c_19',
    block_code: 'C_COMPREHENSION',
    subskill: 'ordering_structure',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'comprehension_structure',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.c_19.prompt',
    instructionKey: 'languages.placementV2.bank.c_19.instruction',
    contentKey: 'languages.placementV2.bank.c_19.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_19.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_19.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_19.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_19.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'c_20',
    block_code: 'C_COMPREHENSION',
    subskill: 'fill_context',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'general_grammar',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.c_20.prompt',
    instructionKey: 'languages.placementV2.bank.c_20.instruction',
    contentKey: 'languages.placementV2.bank.c_20.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.c_20.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.c_20.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.c_20.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.c_20.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'd_01',
    block_code: 'D_ACADEMIC',
    subskill: 'classroom_instructions',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_01.prompt',
    instructionKey: 'languages.placementV2.bank.d_01.instruction',
    contentKey: 'languages.placementV2.bank.d_01.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_01.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_01.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_01.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_01.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'd_02',
    block_code: 'D_ACADEMIC',
    subskill: 'study_task_verbs',
    difficulty: 1 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_02.prompt',
    instructionKey: 'languages.placementV2.bank.d_02.instruction',
    contentKey: 'languages.placementV2.bank.d_02.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_02.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_02.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_02.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_02.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'd_03',
    block_code: 'D_ACADEMIC',
    subskill: 'academic_reading',
    difficulty: 1 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_03.prompt',
    instructionKey: 'languages.placementV2.bank.d_03.instruction',
    contentKey: 'languages.placementV2.bank.d_03.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_03.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_03.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_03.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_03.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'd_04',
    block_code: 'D_ACADEMIC',
    subskill: 'label_instruction_handling',
    difficulty: 1 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: true,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_04.prompt',
    instructionKey: 'languages.placementV2.bank.d_04.instruction',
    contentKey: 'languages.placementV2.bank.d_04.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_04.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_04.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_04.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_04.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'd_05',
    block_code: 'D_ACADEMIC',
    subskill: 'classroom_instructions',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_05.prompt',
    instructionKey: 'languages.placementV2.bank.d_05.instruction',
    contentKey: 'languages.placementV2.bank.d_05.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_05.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_05.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_05.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_05.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'd_06',
    block_code: 'D_ACADEMIC',
    subskill: 'study_task_verbs',
    difficulty: 2 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_06.prompt',
    instructionKey: 'languages.placementV2.bank.d_06.instruction',
    contentKey: 'languages.placementV2.bank.d_06.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_06.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_06.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_06.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_06.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'd_07',
    block_code: 'D_ACADEMIC',
    subskill: 'academic_reading',
    difficulty: 2 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_07.prompt',
    instructionKey: 'languages.placementV2.bank.d_07.instruction',
    contentKey: 'languages.placementV2.bank.d_07.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_07.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_07.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_07.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_07.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'd_08',
    block_code: 'D_ACADEMIC',
    subskill: 'label_instruction_handling',
    difficulty: 2 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_08.prompt',
    instructionKey: 'languages.placementV2.bank.d_08.instruction',
    contentKey: 'languages.placementV2.bank.d_08.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_08.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_08.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_08.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_08.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'd_09',
    block_code: 'D_ACADEMIC',
    subskill: 'classroom_instructions',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_09.prompt',
    instructionKey: 'languages.placementV2.bank.d_09.instruction',
    contentKey: 'languages.placementV2.bank.d_09.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_09.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_09.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_09.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_09.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'd_10',
    block_code: 'D_ACADEMIC',
    subskill: 'study_task_verbs',
    difficulty: 3 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_10.prompt',
    instructionKey: 'languages.placementV2.bank.d_10.instruction',
    contentKey: 'languages.placementV2.bank.d_10.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_10.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_10.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_10.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_10.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'd_11',
    block_code: 'D_ACADEMIC',
    subskill: 'academic_reading',
    difficulty: 3 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_11.prompt',
    instructionKey: 'languages.placementV2.bank.d_11.instruction',
    contentKey: 'languages.placementV2.bank.d_11.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_11.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_11.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_11.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_11.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'd_12',
    block_code: 'D_ACADEMIC',
    subskill: 'label_instruction_handling',
    difficulty: 3 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_12.prompt',
    instructionKey: 'languages.placementV2.bank.d_12.instruction',
    contentKey: 'languages.placementV2.bank.d_12.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_12.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_12.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_12.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_12.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'd_13',
    block_code: 'D_ACADEMIC',
    subskill: 'classroom_instructions',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_13.prompt',
    instructionKey: 'languages.placementV2.bank.d_13.instruction',
    contentKey: 'languages.placementV2.bank.d_13.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_13.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_13.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_13.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_13.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'd_14',
    block_code: 'D_ACADEMIC',
    subskill: 'study_task_verbs',
    difficulty: 4 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_14.prompt',
    instructionKey: 'languages.placementV2.bank.d_14.instruction',
    contentKey: 'languages.placementV2.bank.d_14.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_14.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_14.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_14.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_14.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'd_15',
    block_code: 'D_ACADEMIC',
    subskill: 'academic_reading',
    difficulty: 4 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_15.prompt',
    instructionKey: 'languages.placementV2.bank.d_15.instruction',
    contentKey: 'languages.placementV2.bank.d_15.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_15.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_15.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_15.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_15.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'd_16',
    block_code: 'D_ACADEMIC',
    subskill: 'label_instruction_handling',
    difficulty: 4 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_16.prompt',
    instructionKey: 'languages.placementV2.bank.d_16.instruction',
    contentKey: 'languages.placementV2.bank.d_16.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_16.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_16.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_16.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_16.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'd_17',
    block_code: 'D_ACADEMIC',
    subskill: 'classroom_instructions',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_17.prompt',
    instructionKey: 'languages.placementV2.bank.d_17.instruction',
    contentKey: 'languages.placementV2.bank.d_17.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_17.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_17.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_17.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_17.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'd_18',
    block_code: 'D_ACADEMIC',
    subskill: 'study_task_verbs',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'prep_readiness',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.d_18.prompt',
    instructionKey: 'languages.placementV2.bank.d_18.instruction',
    contentKey: 'languages.placementV2.bank.d_18.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_18.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_18.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_18.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_18.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'd_19',
    block_code: 'D_ACADEMIC',
    subskill: 'academic_reading',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_instructions',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.d_19.prompt',
    instructionKey: 'languages.placementV2.bank.d_19.instruction',
    contentKey: 'languages.placementV2.bank.d_19.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_19.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_19.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_19.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_19.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'd_20',
    block_code: 'D_ACADEMIC',
    subskill: 'label_instruction_handling',
    difficulty: 5 as const,
    format: 'ordering',
    track_tag: 'general',
    gate_item: false,
    weak_area_code: 'academic_reading',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.d_20.prompt',
    instructionKey: 'languages.placementV2.bank.d_20.instruction',
    contentKey: 'languages.placementV2.bank.d_20.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.d_20.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.d_20.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.d_20.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.d_20.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'e_01',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 1 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_01.prompt',
    instructionKey: 'languages.placementV2.bank.e_01.instruction',
    contentKey: 'languages.placementV2.bank.e_01.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_01.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_01.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_01.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_01.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'e_02',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 1 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_02.prompt',
    instructionKey: 'languages.placementV2.bank.e_02.instruction',
    contentKey: 'languages.placementV2.bank.e_02.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_02.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_02.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_02.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_02.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'e_03',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 1 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_03.prompt',
    instructionKey: 'languages.placementV2.bank.e_03.instruction',
    contentKey: 'languages.placementV2.bank.e_03.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_03.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_03.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_03.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_03.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'e_04',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 2 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_04.prompt',
    instructionKey: 'languages.placementV2.bank.e_04.instruction',
    contentKey: 'languages.placementV2.bank.e_04.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_04.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_04.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_04.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_04.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'e_05',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 2 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_05.prompt',
    instructionKey: 'languages.placementV2.bank.e_05.instruction',
    contentKey: 'languages.placementV2.bank.e_05.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_05.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_05.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_05.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_05.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'e_06',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 2 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_06.prompt',
    instructionKey: 'languages.placementV2.bank.e_06.instruction',
    contentKey: 'languages.placementV2.bank.e_06.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_06.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_06.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_06.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_06.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'e_07',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 3 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_07.prompt',
    instructionKey: 'languages.placementV2.bank.e_07.instruction',
    contentKey: 'languages.placementV2.bank.e_07.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_07.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_07.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_07.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_07.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'e_08',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 3 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_08.prompt',
    instructionKey: 'languages.placementV2.bank.e_08.instruction',
    contentKey: 'languages.placementV2.bank.e_08.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_08.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_08.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_08.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_08.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'e_09',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 3 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_09.prompt',
    instructionKey: 'languages.placementV2.bank.e_09.instruction',
    contentKey: 'languages.placementV2.bank.e_09.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_09.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_09.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_09.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_09.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'e_10',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 4 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_10.prompt',
    instructionKey: 'languages.placementV2.bank.e_10.instruction',
    contentKey: 'languages.placementV2.bank.e_10.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_10.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_10.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_10.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_10.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'e_11',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 4 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_11.prompt',
    instructionKey: 'languages.placementV2.bank.e_11.instruction',
    contentKey: 'languages.placementV2.bank.e_11.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_11.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_11.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_11.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_11.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'e_12',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 4 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_12.prompt',
    instructionKey: 'languages.placementV2.bank.e_12.instruction',
    contentKey: 'languages.placementV2.bank.e_12.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_12.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_12.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_12.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_12.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'e_13',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_13.prompt',
    instructionKey: 'languages.placementV2.bank.e_13.instruction',
    contentKey: 'languages.placementV2.bank.e_13.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_13.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_13.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_13.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_13.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'e_14',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_14.prompt',
    instructionKey: 'languages.placementV2.bank.e_14.instruction',
    contentKey: 'languages.placementV2.bank.e_14.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_14.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_14.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_14.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_14.options.d' },
    ],
    correctAnswer: 'c',
  },
  {
    id: 'e_15',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_15.prompt',
    instructionKey: 'languages.placementV2.bank.e_15.instruction',
    contentKey: 'languages.placementV2.bank.e_15.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_15.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_15.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_15.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_15.options.d' },
    ],
    correctAnswer: 'd',
  },
  {
    id: 'e_16',
    block_code: 'E_TRACK',
    subskill: 'medicine_signal',
    difficulty: 5 as const,
    format: 'mcq',
    track_tag: 'medicine',
    gate_item: false,
    weak_area_code: 'track_medicine',
    scoring_weight: 1.0,
    promptKey: 'languages.placementV2.bank.e_16.prompt',
    instructionKey: 'languages.placementV2.bank.e_16.instruction',
    contentKey: 'languages.placementV2.bank.e_16.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_16.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_16.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_16.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_16.options.d' },
    ],
    correctAnswer: 'a',
  },
  {
    id: 'e_17',
    block_code: 'E_TRACK',
    subskill: 'engineering_signal',
    difficulty: 5 as const,
    format: 'cloze',
    track_tag: 'engineering',
    gate_item: false,
    weak_area_code: 'track_engineering',
    scoring_weight: 1.2,
    promptKey: 'languages.placementV2.bank.e_17.prompt',
    instructionKey: 'languages.placementV2.bank.e_17.instruction',
    contentKey: 'languages.placementV2.bank.e_17.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_17.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_17.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_17.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_17.options.d' },
    ],
    correctAnswer: 'b',
  },
  {
    id: 'e_18',
    block_code: 'E_TRACK',
    subskill: 'humanities_signal',
    difficulty: 5 as const,
    format: 'matching',
    track_tag: 'humanities_social',
    gate_item: false,
    weak_area_code: 'track_humanities_social',
    scoring_weight: 1.4,
    promptKey: 'languages.placementV2.bank.e_18.prompt',
    instructionKey: 'languages.placementV2.bank.e_18.instruction',
    contentKey: 'languages.placementV2.bank.e_18.content',
    options: [
      { id: 'a', labelKey: 'languages.placementV2.bank.e_18.options.a' },
      { id: 'b', labelKey: 'languages.placementV2.bank.e_18.options.b' },
      { id: 'c', labelKey: 'languages.placementV2.bank.e_18.options.c' },
      { id: 'd', labelKey: 'languages.placementV2.bank.e_18.options.d' },
    ],
    correctAnswer: 'c',
  },
];