import type { CredentialNamePattern } from '../../types';

// Phase A skeleton — DRAFT patterns. Awaiting truth review before engine wires them.
export const CREDENTIAL_PATTERNS: CredentialNamePattern[] = [
  // EG
  {
    pattern_id: 'EG.thanaweya_amma.ar',
    source_country_code: 'EG',
    match_kind: 'contains',
    match_value: 'الثانوية العامة',
    match_language: 'ar',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'thanaweya_amma',
    confidence_base: 0.9,
    evidence_ids: ['EG.pattern.draft.2026'],
  },
  {
    pattern_id: 'EG.thanaweya_amma.en',
    source_country_code: 'EG',
    match_kind: 'contains',
    match_value: 'thanaweya amma',
    match_language: 'en',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'thanaweya_amma',
    confidence_base: 0.85,
    evidence_ids: ['EG.pattern.draft.2026'],
  },
  {
    pattern_id: 'EG.thanaweya_fanniya.ar',
    source_country_code: 'EG',
    match_kind: 'contains',
    match_value: 'الثانوية الفنية',
    match_language: 'ar',
    maps_to_kind: 'secondary_technical',
    maps_to_subtype: 'thanaweya_fanniya',
    confidence_base: 0.9,
    evidence_ids: ['EG.pattern.draft.2026'],
  },
  // AE
  {
    pattern_id: 'AE.moe_secondary.ar',
    source_country_code: 'AE',
    match_kind: 'contains',
    match_value: 'الثانوية العامة',
    match_language: 'ar',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'moe_secondary',
    confidence_base: 0.85,
    evidence_ids: ['AE.pattern.draft.2026'],
  },
  {
    pattern_id: 'AE.moe_secondary.en',
    source_country_code: 'AE',
    match_kind: 'contains',
    match_value: 'uae secondary',
    match_language: 'en',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'moe_secondary',
    confidence_base: 0.85,
    evidence_ids: ['AE.pattern.draft.2026'],
  },
  // JO
  {
    pattern_id: 'JO.tawjihi.ar',
    source_country_code: 'JO',
    match_kind: 'contains',
    match_value: 'التوجيهي',
    match_language: 'ar',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'tawjihi',
    confidence_base: 0.9,
    evidence_ids: ['JO.pattern.draft.2026'],
  },
  {
    pattern_id: 'JO.tawjihi.en',
    source_country_code: 'JO',
    match_kind: 'contains',
    match_value: 'tawjihi',
    match_language: 'en',
    maps_to_kind: 'secondary_general',
    maps_to_subtype: 'tawjihi',
    confidence_base: 0.9,
    evidence_ids: ['JO.pattern.draft.2026'],
  },
];
