// ═══════════════════════════════════════════════════════════════
// ISO 3166-1 Country Codes — full alpha-3 → alpha-2 + names
// ═══════════════════════════════════════════════════════════════
// Used by MRZ parser to resolve issuing country / nationality.
// Source: ISO 3166-1 (250 entries). Includes territories (HKG, MAC,
// TWN, PSE, ESH, FLK, etc.) so passports from disputed / partial-
// recognition jurisdictions still resolve cleanly.
// ═══════════════════════════════════════════════════════════════

export interface IsoCountry {
  alpha3: string;
  alpha2: string;
  name_en: string;
  name_ar: string;
}

// Compact representation: [alpha3, alpha2, name_en, name_ar]
const RAW: ReadonlyArray<readonly [string, string, string, string]> = [
  ['ABW', 'AW', 'Aruba', 'أروبا'],
  ['AFG', 'AF', 'Afghanistan', 'أفغانستان'],
  ['AGO', 'AO', 'Angola', 'أنغولا'],
  ['AIA', 'AI', 'Anguilla', 'أنغويلا'],
  ['ALA', 'AX', 'Åland Islands', 'جزر آلاند'],
  ['ALB', 'AL', 'Albania', 'ألبانيا'],
  ['AND', 'AD', 'Andorra', 'أندورا'],
  ['ARE', 'AE', 'United Arab Emirates', 'الإمارات العربية المتحدة'],
  ['ARG', 'AR', 'Argentina', 'الأرجنتين'],
  ['ARM', 'AM', 'Armenia', 'أرمينيا'],
  ['ASM', 'AS', 'American Samoa', 'ساموا الأمريكية'],
  ['ATA', 'AQ', 'Antarctica', 'أنتاركتيكا'],
  ['ATF', 'TF', 'French Southern Territories', 'الأقاليم الجنوبية الفرنسية'],
  ['ATG', 'AG', 'Antigua and Barbuda', 'أنتيغوا وباربودا'],
  ['AUS', 'AU', 'Australia', 'أستراليا'],
  ['AUT', 'AT', 'Austria', 'النمسا'],
  ['AZE', 'AZ', 'Azerbaijan', 'أذربيجان'],
  ['BDI', 'BI', 'Burundi', 'بوروندي'],
  ['BEL', 'BE', 'Belgium', 'بلجيكا'],
  ['BEN', 'BJ', 'Benin', 'بنين'],
  ['BES', 'BQ', 'Bonaire, Sint Eustatius and Saba', 'بونير وسينت أوستاتيوس وسابا'],
  ['BFA', 'BF', 'Burkina Faso', 'بوركينا فاسو'],
  ['BGD', 'BD', 'Bangladesh', 'بنغلاديش'],
  ['BGR', 'BG', 'Bulgaria', 'بلغاريا'],
  ['BHR', 'BH', 'Bahrain', 'البحرين'],
  ['BHS', 'BS', 'Bahamas', 'الباهاما'],
  ['BIH', 'BA', 'Bosnia and Herzegovina', 'البوسنة والهرسك'],
  ['BLM', 'BL', 'Saint Barthélemy', 'سان بارتيلمي'],
  ['BLR', 'BY', 'Belarus', 'بيلاروسيا'],
  ['BLZ', 'BZ', 'Belize', 'بليز'],
  ['BMU', 'BM', 'Bermuda', 'برمودا'],
  ['BOL', 'BO', 'Bolivia', 'بوليفيا'],
  ['BRA', 'BR', 'Brazil', 'البرازيل'],
  ['BRB', 'BB', 'Barbados', 'باربادوس'],
  ['BRN', 'BN', 'Brunei Darussalam', 'بروناي'],
  ['BTN', 'BT', 'Bhutan', 'بوتان'],
  ['BVT', 'BV', 'Bouvet Island', 'جزيرة بوفيه'],
  ['BWA', 'BW', 'Botswana', 'بوتسوانا'],
  ['CAF', 'CF', 'Central African Republic', 'جمهورية أفريقيا الوسطى'],
  ['CAN', 'CA', 'Canada', 'كندا'],
  ['CCK', 'CC', 'Cocos (Keeling) Islands', 'جزر كوكوس'],
  ['CHE', 'CH', 'Switzerland', 'سويسرا'],
  ['CHL', 'CL', 'Chile', 'تشيلي'],
  ['CHN', 'CN', 'China', 'الصين'],
  ['CIV', 'CI', "Côte d'Ivoire", 'ساحل العاج'],
  ['CMR', 'CM', 'Cameroon', 'الكاميرون'],
  ['COD', 'CD', 'Congo (Democratic Republic)', 'جمهورية الكونغو الديمقراطية'],
  ['COG', 'CG', 'Congo', 'الكونغو'],
  ['COK', 'CK', 'Cook Islands', 'جزر كوك'],
  ['COL', 'CO', 'Colombia', 'كولومبيا'],
  ['COM', 'KM', 'Comoros', 'جزر القمر'],
  ['CPV', 'CV', 'Cabo Verde', 'الرأس الأخضر'],
  ['CRI', 'CR', 'Costa Rica', 'كوستاريكا'],
  ['CUB', 'CU', 'Cuba', 'كوبا'],
  ['CUW', 'CW', 'Curaçao', 'كوراساو'],
  ['CXR', 'CX', 'Christmas Island', 'جزيرة عيد الميلاد'],
  ['CYM', 'KY', 'Cayman Islands', 'جزر كايمان'],
  ['CYP', 'CY', 'Cyprus', 'قبرص'],
  ['CZE', 'CZ', 'Czechia', 'التشيك'],
  ['DEU', 'DE', 'Germany', 'ألمانيا'],
  ['DJI', 'DJ', 'Djibouti', 'جيبوتي'],
  ['DMA', 'DM', 'Dominica', 'دومينيكا'],
  ['DNK', 'DK', 'Denmark', 'الدنمارك'],
  ['DOM', 'DO', 'Dominican Republic', 'جمهورية الدومينيكان'],
  ['DZA', 'DZ', 'Algeria', 'الجزائر'],
  ['ECU', 'EC', 'Ecuador', 'الإكوادور'],
  ['EGY', 'EG', 'Egypt', 'مصر'],
  ['ERI', 'ER', 'Eritrea', 'إريتريا'],
  ['ESH', 'EH', 'Western Sahara', 'الصحراء الغربية'],
  ['ESP', 'ES', 'Spain', 'إسبانيا'],
  ['EST', 'EE', 'Estonia', 'إستونيا'],
  ['ETH', 'ET', 'Ethiopia', 'إثيوبيا'],
  ['FIN', 'FI', 'Finland', 'فنلندا'],
  ['FJI', 'FJ', 'Fiji', 'فيجي'],
  ['FLK', 'FK', 'Falkland Islands', 'جزر فوكلاند'],
  ['FRA', 'FR', 'France', 'فرنسا'],
  ['FRO', 'FO', 'Faroe Islands', 'جزر فارو'],
  ['FSM', 'FM', 'Micronesia', 'ميكرونيزيا'],
  ['GAB', 'GA', 'Gabon', 'الغابون'],
  ['GBR', 'GB', 'United Kingdom', 'المملكة المتحدة'],
  ['GEO', 'GE', 'Georgia', 'جورجيا'],
  ['GGY', 'GG', 'Guernsey', 'غيرنزي'],
  ['GHA', 'GH', 'Ghana', 'غانا'],
  ['GIB', 'GI', 'Gibraltar', 'جبل طارق'],
  ['GIN', 'GN', 'Guinea', 'غينيا'],
  ['GLP', 'GP', 'Guadeloupe', 'غوادلوب'],
  ['GMB', 'GM', 'Gambia', 'غامبيا'],
  ['GNB', 'GW', 'Guinea-Bissau', 'غينيا بيساو'],
  ['GNQ', 'GQ', 'Equatorial Guinea', 'غينيا الاستوائية'],
  ['GRC', 'GR', 'Greece', 'اليونان'],
  ['GRD', 'GD', 'Grenada', 'غرينادا'],
  ['GRL', 'GL', 'Greenland', 'غرينلاند'],
  ['GTM', 'GT', 'Guatemala', 'غواتيمالا'],
  ['GUF', 'GF', 'French Guiana', 'غيانا الفرنسية'],
  ['GUM', 'GU', 'Guam', 'غوام'],
  ['GUY', 'GY', 'Guyana', 'غيانا'],
  ['HKG', 'HK', 'Hong Kong', 'هونغ كونغ'],
  ['HMD', 'HM', 'Heard Island and McDonald Islands', 'جزر هيرد وماكدونالد'],
  ['HND', 'HN', 'Honduras', 'هندوراس'],
  ['HRV', 'HR', 'Croatia', 'كرواتيا'],
  ['HTI', 'HT', 'Haiti', 'هايتي'],
  ['HUN', 'HU', 'Hungary', 'المجر'],
  ['IDN', 'ID', 'Indonesia', 'إندونيسيا'],
  ['IMN', 'IM', 'Isle of Man', 'جزيرة مان'],
  ['IND', 'IN', 'India', 'الهند'],
  ['IOT', 'IO', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني'],
  ['IRL', 'IE', 'Ireland', 'أيرلندا'],
  ['IRN', 'IR', 'Iran', 'إيران'],
  ['IRQ', 'IQ', 'Iraq', 'العراق'],
  ['ISL', 'IS', 'Iceland', 'آيسلندا'],
  ['ISR', 'IL', 'Israel', 'إسرائيل'],
  ['ITA', 'IT', 'Italy', 'إيطاليا'],
  ['JAM', 'JM', 'Jamaica', 'جامايكا'],
  ['JEY', 'JE', 'Jersey', 'جيرزي'],
  ['JOR', 'JO', 'Jordan', 'الأردن'],
  ['JPN', 'JP', 'Japan', 'اليابان'],
  ['KAZ', 'KZ', 'Kazakhstan', 'كازاخستان'],
  ['KEN', 'KE', 'Kenya', 'كينيا'],
  ['KGZ', 'KG', 'Kyrgyzstan', 'قيرغيزستان'],
  ['KHM', 'KH', 'Cambodia', 'كمبوديا'],
  ['KIR', 'KI', 'Kiribati', 'كيريباتي'],
  ['KNA', 'KN', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس'],
  ['KOR', 'KR', 'South Korea', 'كوريا الجنوبية'],
  ['KWT', 'KW', 'Kuwait', 'الكويت'],
  ['LAO', 'LA', 'Laos', 'لاوس'],
  ['LBN', 'LB', 'Lebanon', 'لبنان'],
  ['LBR', 'LR', 'Liberia', 'ليبيريا'],
  ['LBY', 'LY', 'Libya', 'ليبيا'],
  ['LCA', 'LC', 'Saint Lucia', 'سانت لوسيا'],
  ['LIE', 'LI', 'Liechtenstein', 'ليختنشتاين'],
  ['LKA', 'LK', 'Sri Lanka', 'سريلانكا'],
  ['LSO', 'LS', 'Lesotho', 'ليسوتو'],
  ['LTU', 'LT', 'Lithuania', 'ليتوانيا'],
  ['LUX', 'LU', 'Luxembourg', 'لوكسمبورغ'],
  ['LVA', 'LV', 'Latvia', 'لاتفيا'],
  ['MAC', 'MO', 'Macao', 'ماكاو'],
  ['MAF', 'MF', 'Saint Martin (French)', 'سان مارتن'],
  ['MAR', 'MA', 'Morocco', 'المغرب'],
  ['MCO', 'MC', 'Monaco', 'موناكو'],
  ['MDA', 'MD', 'Moldova', 'مولدوفا'],
  ['MDG', 'MG', 'Madagascar', 'مدغشقر'],
  ['MDV', 'MV', 'Maldives', 'المالديف'],
  ['MEX', 'MX', 'Mexico', 'المكسيك'],
  ['MHL', 'MH', 'Marshall Islands', 'جزر مارشال'],
  ['MKD', 'MK', 'North Macedonia', 'مقدونيا الشمالية'],
  ['MLI', 'ML', 'Mali', 'مالي'],
  ['MLT', 'MT', 'Malta', 'مالطا'],
  ['MMR', 'MM', 'Myanmar', 'ميانمار'],
  ['MNE', 'ME', 'Montenegro', 'الجبل الأسود'],
  ['MNG', 'MN', 'Mongolia', 'منغوليا'],
  ['MNP', 'MP', 'Northern Mariana Islands', 'جزر ماريانا الشمالية'],
  ['MOZ', 'MZ', 'Mozambique', 'موزمبيق'],
  ['MRT', 'MR', 'Mauritania', 'موريتانيا'],
  ['MSR', 'MS', 'Montserrat', 'مونتسرات'],
  ['MTQ', 'MQ', 'Martinique', 'مارتينيك'],
  ['MUS', 'MU', 'Mauritius', 'موريشيوس'],
  ['MWI', 'MW', 'Malawi', 'مالاوي'],
  ['MYS', 'MY', 'Malaysia', 'ماليزيا'],
  ['MYT', 'YT', 'Mayotte', 'مايوت'],
  ['NAM', 'NA', 'Namibia', 'ناميبيا'],
  ['NCL', 'NC', 'New Caledonia', 'كاليدونيا الجديدة'],
  ['NER', 'NE', 'Niger', 'النيجر'],
  ['NFK', 'NF', 'Norfolk Island', 'جزيرة نورفولك'],
  ['NGA', 'NG', 'Nigeria', 'نيجيريا'],
  ['NIC', 'NI', 'Nicaragua', 'نيكاراغوا'],
  ['NIU', 'NU', 'Niue', 'نيوي'],
  ['NLD', 'NL', 'Netherlands', 'هولندا'],
  ['NOR', 'NO', 'Norway', 'النرويج'],
  ['NPL', 'NP', 'Nepal', 'نيبال'],
  ['NRU', 'NR', 'Nauru', 'ناورو'],
  ['NZL', 'NZ', 'New Zealand', 'نيوزيلندا'],
  ['OMN', 'OM', 'Oman', 'عُمان'],
  ['PAK', 'PK', 'Pakistan', 'باكستان'],
  ['PAN', 'PA', 'Panama', 'بنما'],
  ['PCN', 'PN', 'Pitcairn', 'بيتكيرن'],
  ['PER', 'PE', 'Peru', 'بيرو'],
  ['PHL', 'PH', 'Philippines', 'الفلبين'],
  ['PLW', 'PW', 'Palau', 'بالاو'],
  ['PNG', 'PG', 'Papua New Guinea', 'بابوا غينيا الجديدة'],
  ['POL', 'PL', 'Poland', 'بولندا'],
  ['PRI', 'PR', 'Puerto Rico', 'بورتوريكو'],
  ['PRK', 'KP', 'North Korea', 'كوريا الشمالية'],
  ['PRT', 'PT', 'Portugal', 'البرتغال'],
  ['PRY', 'PY', 'Paraguay', 'باراغواي'],
  ['PSE', 'PS', 'Palestine', 'فلسطين'],
  ['PYF', 'PF', 'French Polynesia', 'بولينزيا الفرنسية'],
  ['QAT', 'QA', 'Qatar', 'قطر'],
  ['REU', 'RE', 'Réunion', 'لا ريونيون'],
  ['ROU', 'RO', 'Romania', 'رومانيا'],
  ['RUS', 'RU', 'Russia', 'روسيا'],
  ['RWA', 'RW', 'Rwanda', 'رواندا'],
  ['SAU', 'SA', 'Saudi Arabia', 'المملكة العربية السعودية'],
  ['SDN', 'SD', 'Sudan', 'السودان'],
  ['SEN', 'SN', 'Senegal', 'السنغال'],
  ['SGP', 'SG', 'Singapore', 'سنغافورة'],
  ['SGS', 'GS', 'South Georgia and the South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'],
  ['SHN', 'SH', 'Saint Helena', 'سانت هيلينا'],
  ['SJM', 'SJ', 'Svalbard and Jan Mayen', 'سفالبارد ويان ماين'],
  ['SLB', 'SB', 'Solomon Islands', 'جزر سليمان'],
  ['SLE', 'SL', 'Sierra Leone', 'سيراليون'],
  ['SLV', 'SV', 'El Salvador', 'السلفادور'],
  ['SMR', 'SM', 'San Marino', 'سان مارينو'],
  ['SOM', 'SO', 'Somalia', 'الصومال'],
  ['SPM', 'PM', 'Saint Pierre and Miquelon', 'سان بيير وميكلون'],
  ['SRB', 'RS', 'Serbia', 'صربيا'],
  ['SSD', 'SS', 'South Sudan', 'جنوب السودان'],
  ['STP', 'ST', 'Sao Tome and Principe', 'ساو تومي وبرينسيبي'],
  ['SUR', 'SR', 'Suriname', 'سورينام'],
  ['SVK', 'SK', 'Slovakia', 'سلوفاكيا'],
  ['SVN', 'SI', 'Slovenia', 'سلوفينيا'],
  ['SWE', 'SE', 'Sweden', 'السويد'],
  ['SWZ', 'SZ', 'Eswatini', 'إسواتيني'],
  ['SXM', 'SX', 'Sint Maarten (Dutch)', 'سينت مارتن'],
  ['SYC', 'SC', 'Seychelles', 'سيشل'],
  ['SYR', 'SY', 'Syria', 'سوريا'],
  ['TCA', 'TC', 'Turks and Caicos Islands', 'جزر تركس وكايكوس'],
  ['TCD', 'TD', 'Chad', 'تشاد'],
  ['TGO', 'TG', 'Togo', 'توغو'],
  ['THA', 'TH', 'Thailand', 'تايلاند'],
  ['TJK', 'TJ', 'Tajikistan', 'طاجيكستان'],
  ['TKL', 'TK', 'Tokelau', 'توكيلاو'],
  ['TKM', 'TM', 'Turkmenistan', 'تركمانستان'],
  ['TLS', 'TL', 'Timor-Leste', 'تيمور الشرقية'],
  ['TON', 'TO', 'Tonga', 'تونغا'],
  ['TTO', 'TT', 'Trinidad and Tobago', 'ترينيداد وتوباغو'],
  ['TUN', 'TN', 'Tunisia', 'تونس'],
  ['TUR', 'TR', 'Türkiye', 'تركيا'],
  ['TUV', 'TV', 'Tuvalu', 'توفالو'],
  ['TWN', 'TW', 'Taiwan', 'تايوان'],
  ['TZA', 'TZ', 'Tanzania', 'تنزانيا'],
  ['UGA', 'UG', 'Uganda', 'أوغندا'],
  ['UKR', 'UA', 'Ukraine', 'أوكرانيا'],
  ['UMI', 'UM', 'United States Minor Outlying Islands', 'جزر الولايات المتحدة الصغيرة النائية'],
  ['URY', 'UY', 'Uruguay', 'الأوروغواي'],
  ['USA', 'US', 'United States', 'الولايات المتحدة'],
  ['UZB', 'UZ', 'Uzbekistan', 'أوزبكستان'],
  ['VAT', 'VA', 'Holy See (Vatican)', 'الفاتيكان'],
  ['VCT', 'VC', 'Saint Vincent and the Grenadines', 'سانت فينسنت والغرينادين'],
  ['VEN', 'VE', 'Venezuela', 'فنزويلا'],
  ['VGB', 'VG', 'British Virgin Islands', 'جزر العذراء البريطانية'],
  ['VIR', 'VI', 'U.S. Virgin Islands', 'جزر العذراء الأمريكية'],
  ['VNM', 'VN', 'Vietnam', 'فيتنام'],
  ['VUT', 'VU', 'Vanuatu', 'فانواتو'],
  ['WLF', 'WF', 'Wallis and Futuna', 'واليس وفوتونا'],
  ['WSM', 'WS', 'Samoa', 'ساموا'],
  ['YEM', 'YE', 'Yemen', 'اليمن'],
  ['ZAF', 'ZA', 'South Africa', 'جنوب أفريقيا'],
  ['ZMB', 'ZM', 'Zambia', 'زامبيا'],
  ['ZWE', 'ZW', 'Zimbabwe', 'زيمبابوي'],
  // Common MRZ-only / special codes (ICAO 9303 reserved)
  ['UNO', 'UN', 'United Nations Official', 'الأمم المتحدة'],
  ['UNA', 'UN', 'United Nations Agency', 'وكالة الأمم المتحدة'],
  ['XBA', 'XB', 'African Development Bank', 'بنك التنمية الأفريقي'],
  ['XCC', 'XC', 'Caricom', 'الجماعة الكاريبية'],
  ['XCO', 'XO', 'Common Market for Eastern and Southern Africa', 'الكوميسا'],
  ['XEC', 'XE', 'Economic Community of West African States', 'إيكواس'],
  ['XPO', 'XP', 'Interpol', 'الإنتربول'],
  ['RKS', 'XK', 'Kosovo', 'كوسوفو'],
];

const BY_ALPHA3: Map<string, IsoCountry> = new Map(
  RAW.map(([alpha3, alpha2, name_en, name_ar]) => [alpha3, { alpha3, alpha2, name_en, name_ar }])
);

/**
 * Look up a country by ISO 3166-1 alpha-3 code (case-insensitive).
 * Returns null if unknown — never invents data.
 */
export function lookupCountry(alpha3: string | null | undefined): IsoCountry | null {
  if (!alpha3) return null;
  const key = alpha3.toUpperCase().replace(/</g, '').trim();
  if (!key) return null;
  return BY_ALPHA3.get(key) ?? null;
}

/** Total number of country/territory entries available. */
export const ISO_COUNTRY_COUNT = RAW.length;
