export const russianUniversities = [
  {
    name: "جامعة سيتشينوف موسكو الطبية الحكومية الأولى",
    name_en: "Sechenov First Moscow State Medical University",
    slug: "sechenov-moscow",
    country_code: "RU",
    city: "موسكو",
    founded_year: 1758,
    ranking: 1,
    description: "أقدم وأعرق جامعة طبية في روسيا، تحتل المرتبة الأولى وطنياً في مجال الطب وضمن أفضل 250 عالمياً",
  },
  {
    name: "جامعة لومونوسوف موسكو الحكومية",
    name_en: "Lomonosov Moscow State University",
    slug: "lomonosov-moscow",
    country_code: "RU",
    city: "موسكو",
    founded_year: 1755,
    ranking: 3,
    description: "الجامعة الأكثر شهرة في روسيا، المرتبة 87 عالمياً والثالثة وطنياً في مجال الطب",
  },
  {
    name: "جامعة بيروغوف الروسية الوطنية للبحوث الطبية",
    name_en: "Pirogov Russian National Research Medical University",
    slug: "pirogov-moscow",
    country_code: "RU",
    city: "موسكو",
    founded_year: 1906,
    ranking: 2,
    description: "أكبر المؤسسات الطبية في روسيا وأوروبا، الجامعة الطبية الوحيدة بمكانة جامعة بحثية وطنية",
  },
  {
    name: "جامعة سانت بطرسبرغ الحكومية",
    name_en: "Saint Petersburg State University",
    slug: "spbgu",
    country_code: "RU",
    city: "سانت بطرسبرغ",
    founded_year: 1724,
    ranking: 4,
    description: "واحدة من أقدم الجامعات في روسيا، المرتبة الرابعة وطنياً في مجال الطب",
  },
  {
    name: "جامعة بافلوف الأولى في سانت بطرسبرغ الطبية الحكومية",
    name_en: "Pavlov First Saint Petersburg State Medical University",
    slug: "pavlov-spb",
    country_code: "RU",
    city: "سانت بطرسبرغ",
    founded_year: 1897,
    ranking: 5,
    description: "أول معهد طبي للنساء في روسيا وأوروبا، المرتبة الخامسة وطنياً",
  },
  {
    name: "جامعة الصداقة بين الشعوب",
    name_en: "RUDN University",
    slug: "rudn-moscow",
    country_code: "RU",
    city: "موسكو",
    founded_year: 1960,
    ranking: 9,
    description: "بيئة دولية متنوعة مع طلاب من 155+ دولة، المرتبة التاسعة وطنياً في الطب",
  },
  {
    name: "جامعة شمال غرب الدولة الطبية التي تحمل اسم ميتشنيكوف",
    name_en: "North-Western State Medical University named after Mechnikov",
    slug: "mechnikov-spb",
    country_code: "RU",
    city: "سانت بطرسبرغ",
    founded_year: 2011,
    ranking: 6,
    description: "نتيجة دمج أكاديميتين طبيتين عريقتين، المرتبة السادسة وطنياً",
  },
  {
    name: "جامعة قازان الفيدرالية",
    name_en: "Kazan Federal University",
    slug: "kfu-kazan",
    country_code: "RU",
    city: "قازان",
    founded_year: 1804,
    description: "واحدة من أقدم الجامعات في روسيا، المرتبة 396 عالمياً في الطب",
  },
  {
    name: "جامعة قازان الطبية الحكومية",
    name_en: "Kazan State Medical University",
    slug: "ksmu-kazan",
    country_code: "RU",
    city: "قازان",
    founded_year: 1814,
    ranking: 16,
    description: "واحدة من أقدم ثلاث جامعات طبية في روسيا، طلاب من 57+ دولة",
  },
  {
    name: "جامعة نوفوسيبيرسك الحكومية",
    name_en: "Novosibirsk State University",
    slug: "nsu-novosibirsk",
    country_code: "RU",
    city: "نوفوسيبيرسك",
    founded_year: 1958,
    description: "في المدينة الأكاديمية، ارتباط وثيق بالأكاديمية الروسية للعلوم",
  },
  {
    name: "جامعة سيبيريا الطبية الحكومية",
    name_en: "Siberian State Medical University",
    slug: "ssmu-tomsk",
    country_code: "RU",
    city: "تومسك",
    founded_year: 1878,
    ranking: 11,
    description: "أقدم وأعرق جامعة طبية في سيبيريا، المرتبة 11 وطنياً",
  },
  {
    name: "جامعة باشكير الطبية الحكومية",
    name_en: "Bashkir State Medical University",
    slug: "bsmu-ufa",
    country_code: "RU",
    city: "أوفا",
    founded_year: 1932,
    ranking: 8,
    description: "المرتبة الثامنة وطنياً، قيمة ممتازة مقابل المال",
  },
  {
    name: "جامعة الشرق الأقصى الفيدرالية",
    name_en: "Far Eastern Federal University",
    slug: "fefu-vladivostok",
    country_code: "RU",
    city: "فلاديفوستوك",
    founded_year: 1899,
    description: "حرم جامعي حديث ومذهل، بوابة روسيا لمنطقة آسيا والمحيط الهادئ",
  },
  {
    name: "جامعة أورال الطبية الحكومية",
    name_en: "Ural State Medical University",
    slug: "usmu-yekaterinburg",
    country_code: "RU",
    city: "يكاترينبورغ",
    founded_year: 1930,
    description: "المركز الطبي الرائد في منطقة الأورال، تكاليف منخفضة جداً",
  },
  {
    name: "جامعة فولغوغراد الطبية الحكومية",
    name_en: "Volgograd State Medical University",
    slug: "volgmed",
    country_code: "RU",
    city: "فولغوغراد",
    founded_year: 1935,
    ranking: 19,
    description: "خبرة طويلة مع الطلاب الدوليين منذ 1962، خريجون في 127+ دولة",
  },
  {
    name: "جامعة كورسك الطبية الحكومية",
    name_en: "Kursk State Medical University",
    slug: "ksmu-kursk",
    country_code: "RU",
    city: "كورسك",
    founded_year: 1935,
    description: "من أوائل الجامعات التي قدمت برامج كاملة باللغة الإنجليزية",
  },
  {
    name: "جامعة ألطاي الطبية الحكومية",
    name_en: "Altai State Medical University",
    slug: "asmu-barnaul",
    country_code: "RU",
    city: "بارناول",
    founded_year: 1954,
    description: "تكلفة منخفضة جداً في سيبيريا الغربية، طلاب من 15+ دولة",
  },
  {
    name: "جامعة تفير الطبية الحكومية",
    name_en: "Tver State Medical University",
    slug: "tsmu-tver",
    country_code: "RU",
    city: "تفير",
    founded_year: 1936,
    description: "موقع استراتيجي بين موسكو وسانت بطرسبرغ، تاريخ طويل مع الطلاب الدوليين",
  },
  {
    name: "جامعة فورونيج الطبية الحكومية",
    name_en: "Voronezh State Medical University",
    slug: "vsmu-voronezh",
    country_code: "RU",
    city: "فورونيج",
    ranking: 20,
    description: "المرتبة 20 وطنياً، تدريب عملي مكثف في المستشفيات",
  },
  {
    name: "جامعة ياروسلافل الطبية الحكومية",
    name_en: "Yaroslavl State Medical University",
    slug: "ysmu-yaroslavl",
    country_code: "RU",
    city: "ياروسلافل",
    description: "في مدينة تاريخية جميلة، تعليم طبي عالي الجودة",
  },
  {
    name: "جامعة سامارا الطبية الحكومية",
    name_en: "Samara State Medical University",
    slug: "samsmu",
    country_code: "RU",
    city: "سامارا",
    founded_year: 1919,
    description: "واحدة من أكبر الجامعات الطبية، برامج باللغة الإنجليزية بتكلفة منخفضة جداً",
  },
  {
    name: "جامعة أورينبورغ الطبية الحكومية",
    name_en: "Orenburg State Medical University",
    slug: "osmu-orenburg",
    country_code: "RU",
    city: "أورينبورغ",
    founded_year: 1944,
    description: "وجهة شائعة للطلاب الهنود، أكثر من 1200 طالب هندي",
  },
  {
    name: "جامعة ريازان الطبية الحكومية",
    name_en: "Ryazan State Medical University",
    slug: "rsmu-ryazan",
    country_code: "RU",
    city: "ريازان",
    ranking: 17,
    description: "سميت على اسم العالم إيفان بافلوف الحائز على نوبل، المرتبة 17 وطنياً",
  },
  {
    name: "جامعة سمولينسك الطبية الحكومية",
    name_en: "Smolensk State Medical University",
    slug: "ssmu-smolensk",
    country_code: "RU",
    city: "سمولينسك",
    founded_year: 1920,
    description: "كلية خاصة للطلاب الدوليين، برامج باللغة الإنجليزية",
  },
  {
    name: "جامعة كوبان الطبية الحكومية",
    name_en: "Kuban State Medical University",
    slug: "ksmu-krasnodar",
    country_code: "RU",
    city: "كراسنودار",
    ranking: 18,
    description: "في جنوب روسيا، من أقدم كليات الطب، المرتبة 18 وطنياً",
  },
  {
    name: "جامعة روستوف الطبية الحكومية",
    name_en: "Rostov State Medical University",
    slug: "rostgmu",
    country_code: "RU",
    city: "روستوف-نا-دونو",
    ranking: 13,
    description: "أكبر مركز للبحوث الطبية في جنوب روسيا، المرتبة 13 وطنياً",
  },
  {
    name: "جامعة ساراتوف الطبية الحكومية",
    name_en: "Saratov State Medical University",
    slug: "ssmu-saratov",
    country_code: "RU",
    city: "ساراتوف",
    founded_year: 1909,
    ranking: 15,
    description: "برامج بلغات متعددة بما في ذلك الفرنسية، المرتبة 15 وطنياً",
  },
  {
    name: "جامعة القرم الفيدرالية",
    name_en: "Crimea Federal University",
    slug: "cfu-simferopol",
    country_code: "RU",
    city: "سيمفيروبول",
    description: "المركز التعليمي الرئيسي في شبه جزيرة القرم، تكاليف منخفضة جداً",
  },
  {
    name: "جامعة سانت بطرسبرغ الحكومية لطب الأطفال",
    name_en: "Saint Petersburg State Pediatric Medical University",
    slug: "spbgpmu",
    country_code: "RU",
    city: "سانت بطرسبرغ",
    founded_year: 1905,
    ranking: 10,
    description: "أقدم جامعة لطب الأطفال في العالم، المرتبة 10 وطنياً",
  },
  {
    name: "جامعة كيروف الطبية الحكومية",
    name_en: "Kirov State Medical University",
    slug: "ksmu-kirov",
    country_code: "RU",
    city: "كيروف",
    description: "تعليم طبي معتمد بتكلفة منخفضة جداً",
  },
];
