// ─── Prep Service Definitions ───
import type { PrepServiceCard } from './types';

export const PREP_SERVICES: PrepServiceCard[] = [
  {
    id: 'ielts_prep',
    type: 'ielts_prep',
    title_key: 'readiness.services.ielts_prep',
    description_key: 'readiness.services.ielts_prep_desc',
    icon: 'languages',
    features_keys: [
      'readiness.services.features.practice_tests',
      'readiness.services.features.expert_feedback',
      'readiness.services.features.score_guarantee',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    linked_gap_categories: ['english_test'],
  },
  {
    id: 'toefl_prep',
    type: 'toefl_prep',
    title_key: 'readiness.services.toefl_prep',
    description_key: 'readiness.services.toefl_prep_desc',
    icon: 'languages',
    features_keys: [
      'readiness.services.features.practice_tests',
      'readiness.services.features.expert_feedback',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    linked_gap_categories: ['english_test'],
  },
  {
    id: 'duolingo_prep',
    type: 'duolingo_prep',
    title_key: 'readiness.services.duolingo_prep',
    description_key: 'readiness.services.duolingo_prep_desc',
    icon: 'globe',
    features_keys: [
      'readiness.services.features.flexible_schedule',
      'readiness.services.features.affordable',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    linked_gap_categories: ['english_test'],
  },
  {
    id: 'pte_prep',
    type: 'pte_prep',
    title_key: 'readiness.services.pte_prep',
    description_key: 'readiness.services.pte_prep_desc',
    icon: 'mic',
    features_keys: [
      'readiness.services.features.computer_based',
      'readiness.services.features.quick_results',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    linked_gap_categories: ['english_test'],
  },
  {
    id: 'sat_prep',
    type: 'sat_prep',
    title_key: 'readiness.services.sat_prep',
    description_key: 'readiness.services.sat_prep_desc',
    icon: 'calculator',
    features_keys: [
      'readiness.services.features.math_verbal',
      'readiness.services.features.practice_tests',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    linked_gap_categories: ['academic_test'],
  },
  {
    id: 'act_prep',
    type: 'act_prep',
    title_key: 'readiness.services.act_prep',
    description_key: 'readiness.services.act_prep_desc',
    icon: 'pencil-ruler',
    features_keys: [
      'readiness.services.features.science_section',
      'readiness.services.features.practice_tests',
    ],
    cta_key: 'readiness.services.start_prep',
    available: false,
    coming_soon: true,
    linked_gap_categories: ['academic_test'],
  },
  {
    id: 'gre_prep',
    type: 'gre_prep',
    title_key: 'readiness.services.gre_prep',
    description_key: 'readiness.services.gre_prep_desc',
    icon: 'brain',
    features_keys: [
      'readiness.services.features.analytical_writing',
      'readiness.services.features.quantitative',
    ],
    cta_key: 'readiness.services.start_prep',
    available: false,
    coming_soon: true,
    linked_gap_categories: ['academic_test'],
  },
  {
    id: 'gmat_prep',
    type: 'gmat_prep',
    title_key: 'readiness.services.gmat_prep',
    description_key: 'readiness.services.gmat_prep_desc',
    icon: 'bar-chart-3',
    features_keys: [
      'readiness.services.features.data_insights',
      'readiness.services.features.verbal_quant',
    ],
    cta_key: 'readiness.services.start_prep',
    available: false,
    coming_soon: true,
    linked_gap_categories: ['academic_test'],
  },
  {
    id: 'foundation_support',
    type: 'foundation_support',
    title_key: 'readiness.services.foundation_support',
    description_key: 'readiness.services.foundation_support_desc',
    icon: 'graduation-cap',
    features_keys: [
      'readiness.services.features.university_prep',
      'readiness.services.features.credit_transfer',
    ],
    cta_key: 'readiness.services.learn_more',
    available: true,
    linked_gap_categories: ['foundation_required', 'gpa_below_threshold'],
  },
  {
    id: 'subject_remediation',
    type: 'subject_remediation',
    title_key: 'readiness.services.subject_remediation',
    description_key: 'readiness.services.subject_remediation_desc',
    icon: 'book-open',
    features_keys: [
      'readiness.services.features.math',
      'readiness.services.features.science',
    ],
    cta_key: 'readiness.services.start_prep',
    available: true,
    coming_soon: true,
    linked_gap_categories: ['prerequisite_subject'],
  },
  {
    id: 'document_readiness',
    type: 'document_readiness',
    title_key: 'readiness.services.document_readiness',
    description_key: 'readiness.services.document_readiness_desc',
    icon: 'file-check',
    features_keys: [
      'readiness.services.features.translation',
      'readiness.services.features.notarization',
    ],
    cta_key: 'readiness.services.get_help',
    available: true,
    linked_gap_categories: ['document_missing'],
  },
];
