-- Update country names to Arabic
UPDATE countries SET name = 'أستراليا' WHERE slug = 'australia';
UPDATE countries SET name = 'كندا' WHERE slug = 'ca';
UPDATE countries SET name = 'الصين' WHERE slug = 'china';
UPDATE countries SET name = 'ألمانيا' WHERE slug = 'germany';
UPDATE countries SET name = 'اليابان' WHERE slug = 'japan';
UPDATE countries SET name = 'هولندا' WHERE slug = 'netherlands';
UPDATE countries SET name = 'روسيا' WHERE slug = 'russia';
UPDATE countries SET name = 'تركيا' WHERE slug = 'turkey';
UPDATE countries SET name = 'المملكة المتحدة' WHERE slug = 'uk';
UPDATE countries SET name = 'الولايات المتحدة' WHERE slug = 'usa';
UPDATE countries SET name = 'فرنسا' WHERE slug = 'france';
UPDATE countries SET name = 'إيطاليا' WHERE slug = 'italy';
UPDATE countries SET name = 'إسبانيا' WHERE slug = 'spain';
UPDATE countries SET name = 'البرتغال' WHERE slug = 'portugal';
UPDATE countries SET name = 'السويد' WHERE slug = 'sweden';
UPDATE countries SET name = 'النرويج' WHERE slug = 'norway';
UPDATE countries SET name = 'الدنمارك' WHERE slug = 'denmark';
UPDATE countries SET name = 'فنلندا' WHERE slug = 'finland';
UPDATE countries SET name = 'بولندا' WHERE slug = 'poland';
UPDATE countries SET name = 'التشيك' WHERE slug = 'czech';
UPDATE countries SET name = 'النمسا' WHERE slug = 'austria';
UPDATE countries SET name = 'سويسرا' WHERE slug = 'switzerland';
UPDATE countries SET name = 'بلجيكا' WHERE slug = 'belgium';
UPDATE countries SET name = 'أيرلندا' WHERE slug = 'ireland';
UPDATE countries SET name = 'نيوزيلندا' WHERE slug = 'new-zealand';
UPDATE countries SET name = 'كوريا الجنوبية' WHERE slug = 'south-korea';
UPDATE countries SET name = 'سنغافورة' WHERE slug = 'singapore';
UPDATE countries SET name = 'ماليزيا' WHERE slug = 'malaysia';
UPDATE countries SET name = 'الهند' WHERE slug = 'india';
UPDATE countries SET name = 'الإمارات' WHERE slug = 'uae';
UPDATE countries SET name = 'السعودية' WHERE slug = 'saudi';
UPDATE countries SET name = 'مصر' WHERE slug = 'egypt';
UPDATE countries SET name = 'الأردن' WHERE slug = 'jordan';
UPDATE countries SET name = 'لبنان' WHERE slug = 'lebanon';
UPDATE countries SET name = 'المغرب' WHERE slug = 'morocco';
UPDATE countries SET name = 'تونس' WHERE slug = 'tunisia';