-- Phase B2.2: Delete all legacy one-time events from pipeline_health_events
DELETE FROM pipeline_health_events
WHERE event_type IN (
  'field_published',
  'studio_uniranks_saved',
  'uniranks_programs_page_scrape_failed',
  'uniranks_programs_page_scraped',
  'uniranks_university_partial',
  'uniranks_university_quarantined',
  'uniranks_university_done',
  'uniranks_university_no_programs',
  'uniranks_scrape_failed',
  'detail_fetch_failed',
  'detail_extract_failed',
  'detail_status_update_failed',
  'detail_write_draft_failed',
  'batch_complete',
  'batch_error',
  'd5_enrich_batch_done',
  'd5_program_details_start',
  'd5_program_details_done',
  'd5_programs_batch_start',
  'd5_programs_batch_done',
  'd5_employment_start',
  'd5_employment_done',
  'd5_useful_info_start',
  'd5_useful_info_done',
  'd5_index_fetch_done',
  'd5_index_match_done',
  'd5_map_programs_start',
  'd5_map_programs_done',
  'd5_publish_start',
  'd5_publish_done',
  'publish_programs'
);