INSERT INTO translation_glossary (term_key, source_locale, target_locale, source_text, target_text, domain) VALUES
('discipline.accounting','en','ar','Accounting','المحاسبة','higher-ed'),
('discipline.aerospace','en','ar','Aerospace Engineering','هندسة الفضاء','higher-ed'),
('discipline.agriculture','en','ar','Agriculture','الزراعة','higher-ed'),
('discipline.animation','en','ar','Animation','الرسوم المتحركة','higher-ed'),
('discipline.anthropology','en','ar','Anthropology','الأنثروبولوجيا','higher-ed'),
('discipline.archaeology','en','ar','Archaeology','علم الآثار','higher-ed'),
('discipline.architecture','en','ar','Architecture','العمارة','higher-ed'),
('discipline.arts','en','ar','Arts','الآداب','higher-ed'),
('discipline.astronomy','en','ar','Astronomy','علم الفلك','higher-ed'),
('discipline.biology','en','ar','Biology','الأحياء','higher-ed'),
('discipline.biomedical','en','ar','Biomedical Engineering','الهندسة الطبية الحيوية','higher-ed'),
('discipline.biotechnology','en','ar','Biotechnology','التكنولوجيا الحيوية','higher-ed'),
('discipline.business','en','ar','Business','إدارة الأعمال','higher-ed'),
('discipline.business_admin','en','ar','Business Administration','إدارة الأعمال','higher-ed'),
('discipline.chemistry','en','ar','Chemistry','الكيمياء','higher-ed'),
('discipline.civil_eng','en','ar','Civil Engineering','الهندسة المدنية','higher-ed'),
('discipline.communication','en','ar','Communication','الاتصال','higher-ed'),
('discipline.computer_eng','en','ar','Computer Engineering','هندسة الحاسوب','higher-ed'),
('discipline.computer_science','en','ar','Computer Science','علوم الحاسوب','higher-ed'),
('discipline.criminal_justice','en','ar','Criminal Justice','العدالة الجنائية','higher-ed'),
('discipline.cybersecurity','en','ar','Cybersecurity','الأمن السيبراني','higher-ed'),
('discipline.data_science','en','ar','Data Science','علم البيانات','higher-ed'),
('discipline.dentistry','en','ar','Dentistry','طب الأسنان','higher-ed'),
('discipline.design','en','ar','Design','التصميم','higher-ed'),
('discipline.economics','en','ar','Economics','الاقتصاد','higher-ed'),
('discipline.education','en','ar','Education','التربية','higher-ed'),
('discipline.electrical_eng','en','ar','Electrical Engineering','الهندسة الكهربائية','higher-ed'),
('discipline.engineering','en','ar','Engineering','الهندسة','higher-ed'),
('discipline.english','en','ar','English','اللغة الإنجليزية','higher-ed'),
('discipline.environmental','en','ar','Environmental Science','العلوم البيئية','higher-ed'),
('discipline.fashion','en','ar','Fashion','الأزياء','higher-ed'),
('discipline.film','en','ar','Film','السينما','higher-ed'),
('discipline.finance','en','ar','Finance','التمويل','higher-ed'),
('discipline.fine_arts','en','ar','Fine Arts','الفنون الجميلة','higher-ed'),
('discipline.food_science','en','ar','Food Science','علوم الغذاء','higher-ed'),
('discipline.geography','en','ar','Geography','الجغرافيا','higher-ed'),
('discipline.geology','en','ar','Geology','الجيولوجيا','higher-ed'),
('discipline.graphic_design','en','ar','Graphic Design','التصميم الجرافيكي','higher-ed'),
('discipline.health','en','ar','Health Sciences','العلوم الصحية','higher-ed'),
('discipline.history','en','ar','History','التاريخ','higher-ed'),
('discipline.hospitality','en','ar','Hospitality','الضيافة','higher-ed'),
('discipline.human_resources','en','ar','Human Resources','الموارد البشرية','higher-ed'),
('discipline.industrial_eng','en','ar','Industrial Engineering','الهندسة الصناعية','higher-ed'),
('discipline.info_systems','en','ar','Information Systems','نظم المعلومات','higher-ed'),
('discipline.info_tech','en','ar','Information Technology','تقنية المعلومات','higher-ed'),
('discipline.international_relations','en','ar','International Relations','العلاقات الدولية','higher-ed'),
('discipline.journalism','en','ar','Journalism','الصحافة','higher-ed'),
('discipline.law','en','ar','Law','القانون','higher-ed'),
('discipline.linguistics','en','ar','Linguistics','اللسانيات','higher-ed'),
('discipline.management','en','ar','Management','الإدارة','higher-ed'),
('discipline.marketing','en','ar','Marketing','التسويق','higher-ed'),
('discipline.mathematics','en','ar','Mathematics','الرياضيات','higher-ed'),
('discipline.mechanical_eng','en','ar','Mechanical Engineering','الهندسة الميكانيكية','higher-ed'),
('discipline.media','en','ar','Media','الإعلام','higher-ed'),
('discipline.medicine','en','ar','Medicine','الطب','higher-ed'),
('discipline.music','en','ar','Music','الموسيقى','higher-ed'),
('discipline.nursing','en','ar','Nursing','التمريض','higher-ed'),
('discipline.nutrition','en','ar','Nutrition','التغذية','higher-ed'),
('discipline.pharmacy','en','ar','Pharmacy','الصيدلة','higher-ed'),
('discipline.philosophy','en','ar','Philosophy','الفلسفة','higher-ed'),
('discipline.physics','en','ar','Physics','الفيزياء','higher-ed'),
('discipline.political_science','en','ar','Political Science','العلوم السياسية','higher-ed'),
('discipline.psychology','en','ar','Psychology','علم النفس','higher-ed'),
('discipline.public_health','en','ar','Public Health','الصحة العامة','higher-ed'),
('discipline.sociology','en','ar','Sociology','علم الاجتماع','higher-ed'),
('discipline.software_eng','en','ar','Software Engineering','هندسة البرمجيات','higher-ed'),
('discipline.statistics','en','ar','Statistics','الإحصاء','higher-ed'),
('discipline.supply_chain','en','ar','Supply Chain Management','إدارة سلسلة الإمداد','higher-ed'),
('discipline.theology','en','ar','Theology','اللاهوت','higher-ed'),
('discipline.tourism','en','ar','Tourism','السياحة','higher-ed'),
('discipline.urban_planning','en','ar','Urban Planning','التخطيط العمراني','higher-ed'),
('discipline.veterinary','en','ar','Veterinary','الطب البيطري','higher-ed'),
('modifier.and','en','ar','and','و','higher-ed'),
('modifier.applied','en','ar','Applied','التطبيقية','higher-ed'),
('modifier.clinical','en','ar','Clinical','السريرية','higher-ed'),
('modifier.computational','en','ar','Computational','الحوسبية','higher-ed'),
('modifier.digital','en','ar','Digital','الرقمية','higher-ed'),
('modifier.environmental','en','ar','Environmental','البيئية','higher-ed'),
('modifier.international','en','ar','International','الدولية','higher-ed'),
('modifier.marine','en','ar','Marine','البحرية','higher-ed'),
('modifier.molecular','en','ar','Molecular','الجزيئية','higher-ed'),
('modifier.nuclear','en','ar','Nuclear','النووية','higher-ed'),
('modifier.public','en','ar','Public','العامة','higher-ed'),
('modifier.sciences','en','ar','Sciences','العلوم','higher-ed'),
('modifier.studies','en','ar','Studies','الدراسات','higher-ed'),
('modifier.technology','en','ar','Technology','التكنولوجيا','higher-ed')
ON CONFLICT (term_key, source_locale, target_locale) DO NOTHING;