// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkivavsxbvwtnkgxaufa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraXZhdnN4YnZ3dG5rZ3hhdWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5ODY3NzYsImV4cCI6MjA5MTU2Mjc3Nn0.jYZe5WnjINZdXT9tmizxxfbd1jT4wJ277kdD1nTl1Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});